const now = "2026-03-26T10:00:00.000Z";

function createSeedData() {
  const projectId = "proj_demo_001";
  const storyboardIds = ["sb_001", "sb_002", "sb_003"];

  return {
    projects: [
      {
        id: projectId,
        title: "城南旧梦 漫剧样片",
        summary: "民国雨夜题材的漫剧创作项目，用于联调七节点工作流。",
        status: "in_production",
        coverUrl: "https://mock.assets.local/projects/proj_demo_001/cover.jpg",
        organizationId: "org_demo_001",
        currentStep: "storyboards",
        progressPercent: 58,
        budgetCredits: 1280,
        directorAgentName: "小楼导演 Agent",
        createdAt: now,
        updatedAt: now,
      },
    ],
    settingsByProjectId: {
      [projectId]: {
        projectId,
        tone: "克制、潮湿、旧上海电影感",
        genre: "都市情感",
        targetDurationSeconds: 95,
        aspectRatio: "9:16",
        visualStyle: "电影颗粒、柔光、霓虹雨夜",
        audience: "",
        modelProfile: "plus",
        language: "zh-CN",
        updatedAt: now,
      },
    },
    scriptsByProjectId: {
      [projectId]: {
        id: "script_001",
        projectId,
        version: 4,
        title: "雨夜重逢",
        content:
          "第一幕：阿宁撑着蓝伞穿过城南雨巷。第二幕：周叙从照相馆推门而出。第三幕：两人在霓虹倒影里对视，旧日误会再次翻涌。",
        updatedAt: now,
      },
    },
    assetsByProjectId: {
      [projectId]: [
        {
          id: "asset_char_001",
          projectId,
          assetType: "character",
          name: "阿宁",
          description: "20岁，蓝色旗袍，短卷发，神情克制。",
          previewUrl: "https://mock.assets.local/characters/aning.jpg",
          scope: "seed",
          createdAt: now,
        },
        {
          id: "asset_char_002",
          projectId,
          assetType: "character",
          name: "周叙",
          description: "26岁，黑风衣，旧相机随身，偏忧郁。",
          previewUrl: "https://mock.assets.local/characters/zhouxu.jpg",
          scope: "seed",
          createdAt: now,
        },
        {
          id: "asset_scene_001",
          projectId,
          assetType: "scene",
          name: "城南雨巷",
          description: "石板路、霓虹倒影、潮湿空气。",
          previewUrl: "https://mock.assets.local/scenes/alley-rain.jpg",
          scope: "seed",
          createdAt: now,
        },
      ],
    },
    storyboardsByProjectId: {
      [projectId]: [
        {
          id: storyboardIds[0],
          projectId,
          shotNo: 1,
          title: "雨夜奔走",
          script: "阿宁撑着蓝伞在巷子里快步前行，雨滴打在伞沿。",
          imageStatus: "ready",
          videoStatus: "draft",
          durationSeconds: 4,
          promptSummary: "蓝旗袍少女，雨夜巷口，电影感",
          imageUrl: "https://mock.assets.local/storyboards/sb_001.jpg",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: storyboardIds[1],
          projectId,
          shotNo: 2,
          title: "照相馆门开",
          script: "周叙推开老照相馆木门，暖黄灯光落在雨雾里。",
          imageStatus: "ready",
          videoStatus: "queued",
          durationSeconds: 5,
          promptSummary: "老式照相馆，黑风衣青年，暖黄灯光",
          imageUrl: "https://mock.assets.local/storyboards/sb_002.jpg",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: storyboardIds[2],
          projectId,
          shotNo: 3,
          title: "巷口对视",
          script: "两人在霓虹倒影里停下，对视一瞬，空气凝住。",
          imageStatus: "draft",
          videoStatus: "draft",
          durationSeconds: 6,
          promptSummary: "双人情绪对视，霓虹水面，慢镜头感",
          imageUrl: null,
          createdAt: now,
          updatedAt: now,
        },
      ],
    },
    videosByProjectId: {
      [projectId]: [
        {
          id: "video_001",
          projectId,
          storyboardId: storyboardIds[0],
          version: 2,
          status: "ready",
          durationSeconds: 4,
          videoUrl: "https://mock.assets.local/videos/video_001.mp4",
          thumbnailUrl: "https://mock.assets.local/videos/video_001.jpg",
          createdAt: now,
          updatedAt: now,
        },
      ],
    },
    dubbingsByProjectId: {
      [projectId]: [
        {
          id: "dub_001",
          projectId,
          storyboardId: storyboardIds[0],
          speakerName: "阿宁",
          voicePreset: "female_calm_01",
          text: "雨再大，也总会有人等在街角。",
          status: "ready",
          audioUrl: "https://mock.assets.local/audio/dub_001.mp3",
          createdAt: now,
          updatedAt: now,
        },
      ],
    },
    timelinesByProjectId: {
      [projectId]: {
        projectId,
        version: 3,
        totalDurationSeconds: 15,
        tracks: [
          { id: "track_video", type: "video", itemCount: 3 },
          { id: "track_voice", type: "voice", itemCount: 1 },
          { id: "track_music", type: "music", itemCount: 1 },
          { id: "track_subtitle", type: "subtitle", itemCount: 1 },
        ],
        updatedAt: now,
      },
    },
    createStudioImages: [
      {
        id: "create_img_001",
        prompt: "霓虹夜色中的城市街头少女",
        model: "Wan 2.6 T2I",
        style: "电影感",
        aspectRatio: "16:9",
        resolution: "2K",
        imageUrl: "https://mock.assets.local/create/images/create_img_001.jpg",
        createdAt: now,
      },
    ],
    createStudioVideos: [
      {
        id: "create_vid_001",
        prompt: "镜头缓慢推进，雨水倒影在潮湿路面闪烁",
        model: "WanX 2.1 I2V Turbo",
        duration: "3s",
        aspectRatio: "16:9",
        resolution: "1080p",
        thumbnailUrl: "https://mock.assets.local/create/videos/create_vid_001.jpg",
        videoUrl: "https://mock.assets.local/create/videos/create_vid_001.mp4",
        createdAt: now,
      },
    ],
    apiCenterConfig: {
      vendors: [
        {
          id: "aliyun-bailian",
          name: "Alibaba Cloud Bailian",
          connected: true,
          lastCheckedAt: now,
          testedAt: now,
          region: "cn-beijing",
          supportedDomains: ["text", "vision", "image", "video", "audio"],
          models: [
            {
              id: "qwen-plus",
              name: "Qwen Plus",
              domain: "text",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "qwen-max",
              name: "Qwen Max",
              domain: "text",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "qwen-vl-plus",
              name: "Qwen VL Plus",
              domain: "vision",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "wan2.6-t2i",
              name: "Wan 2.6 T2I",
              domain: "image",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "wanx2.1-imageedit",
              name: "WanX 2.1 Image Edit",
              domain: "image",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "wanx2.1-i2v-turbo",
              name: "WanX 2.1 I2V Turbo",
              domain: "video",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "wanx2.1-i2v-plus",
              name: "WanX 2.1 I2V Plus",
              domain: "video",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "wan2.2-kf2v-flash",
              name: "Wan 2.2 KF2V Flash",
              domain: "video",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "wan2.2-s2v-detect",
              name: "Wan 2.2 S2V Detect",
              domain: "vision",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "wan2.2-s2v",
              name: "Wan 2.2 S2V",
              domain: "video",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
            {
              id: "cosyvoice-v3-flash",
              name: "CosyVoice V3 Flash",
              domain: "audio",
              inputPrice: "official",
              outputPrice: "official",
              enabled: true,
            },
          ],
        },
      ],
      defaults: {
        textModelId: "qwen-plus",
        visionModelId: "qwen-vl-plus",
        imageModelId: "wan2.6-t2i",
        videoModelId: "wanx2.1-i2v-turbo",
        audioModelId: "cosyvoice-v3-flash",
      },
      strategies: {
        lite: "qwen-plus + wanx2.1-i2v-turbo + cosyvoice-v3-flash",
        standard: "qwen-plus + wan2.6-t2i + wan2.2-kf2v-flash",
        plus: "qwen-max + wan2.6-t2i + wan2.2-s2v",
      },
      nodeAssignments: [
        {
          nodeCode: "global",
          nodeName: "1 全局设定",
          primaryModelId: "qwen-plus",
          fallbackModelIds: ["qwen-max"],
          notes: "做设定归一化、风格补全和生成约束整理。",
        },
        {
          nodeCode: "script",
          nodeName: "2 故事剧本",
          primaryModelId: "qwen-plus",
          fallbackModelIds: ["qwen-max"],
          notes: "做剧本扩写、改写、对白润色和分段。",
        },
        {
          nodeCode: "assets",
          nodeName: "3 场景角色道具",
          primaryModelId: "qwen-plus",
          fallbackModelIds: [],
          notes: "从剧本和参考图抽取角色、场景、道具结构。",
        },
        {
          nodeCode: "storyboard_script",
          nodeName: "4 分镜脚本",
          primaryModelId: "qwen-plus",
          fallbackModelIds: ["qwen-max"],
          notes: "输出镜头拆解和分镜头提示词。",
        },
        {
          nodeCode: "storyboard_image",
          nodeName: "4 分镜图生成",
          primaryModelId: "wan2.6-t2i",
          fallbackModelIds: ["wanx2.1-imageedit"],
          notes: "单镜头重绘、换装、局部编辑走图像模型。",
        },
        {
          nodeCode: "video_i2v",
          nodeName: "5 分镜视频(图生视频)",
          primaryModelId: "wanx2.1-i2v-turbo",
          fallbackModelIds: [],
          notes: "一期主模式，成本更稳。",
        },
        {
          nodeCode: "video_kf2v",
          nodeName: "5 分镜视频(首尾帧)",
          primaryModelId: "wan2.2-kf2v-flash",
          fallbackModelIds: [],
          notes: "首尾帧驱动的镜头过渡视频。",
        },
        {
          nodeCode: "dubbing_tts",
          nodeName: "6 配音",
          primaryModelId: "cosyvoice-v3-flash",
          fallbackModelIds: [],
          notes: "中文多音色配音，一期优先性价比。",
        },
        {
          nodeCode: "lip_sync",
          nodeName: "6 对口型",
          primaryModelId: "wan2.2-s2v",
          fallbackModelIds: ["wan2.2-s2v-detect"],
          notes: "先做人像检测，再做音频驱动口型。",
        },
        {
          nodeCode: "preview",
          nodeName: "7 视频预览与导出",
          primaryModelId: null,
          fallbackModelIds: [],
          notes: "导出链路走 FFmpeg 和系统流水线，不依赖大模型。",
        },
      ],
      toolboxAssignments: [
        {
          nodeCode: "character_replace",
          nodeName: "人物替换",
          primaryModelId: "wanx2.1-imageedit",
          fallbackModelIds: ["wan2.6-t2i"],
          notes: "角色换装、换脸、局部重绘优先走图像编辑。",
        },
        {
          nodeCode: "motion_transfer",
          nodeName: "动作迁移",
          primaryModelId: "wanx2.1-i2v-turbo",
          fallbackModelIds: ["wan2.2-kf2v-flash"],
          notes: "先用低成本视频模型验证动作迁移链路。",
        },
        {
          nodeCode: "upscale_restore",
          nodeName: "超清修复",
          primaryModelId: "wanx2.1-imageedit",
          fallbackModelIds: [],
          notes: "一期先用图像增强链路承接静帧修复。",
        },
      ],
    },
    wallet: {
      ownerId: "user_demo_001",
      creditsAvailable: 5820,
      creditsFrozen: 320,
      currency: "credits",
      updatedAt: now,
    },
    walletRechargeOrders: [],
    enterpriseApplications: [
      {
        id: "ent_app_001",
        companyName: "小楼影像工作室",
        contactName: "林舟",
        contactPhone: "13800000000",
        status: "under_review",
        createdAt: now,
      },
    ],
    tasks: [
      {
        id: "task_demo_001",
        type: "video_generate",
        domain: "storyboards",
        projectId,
        storyboardId: storyboardIds[1],
        status: "running",
        progressPercent: 62,
        currentStage: "video_provider_rendering",
        etaSeconds: 48,
        inputSummary: "镜头 2 图生视频生成",
        outputSummary: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    toolboxCapabilities: [
      {
        code: "character_replace",
        name: "人物替换",
        status: "mock_ready",
        queue: "image-gpu",
        description: "在保留镜头构图的前提下替换主角身份、服装与角色特征。",
      },
      {
        code: "motion_transfer",
        name: "动作迁移",
        status: "mock_ready",
        queue: "video-gpu",
        description: "把参考动作迁移到指定角色或现有镜头视频。",
      },
      {
        code: "upscale_restore",
        name: "超清修复",
        status: "mock_ready",
        queue: "image-cpu",
        description: "对低清镜头图、视频帧或导出视频做超分修复。",
      },
      {
        code: "toolbox_reserved",
        name: "待开发暂存",
        status: "placeholder",
        queue: "unassigned",
        description: "未来工具型能力的暂存区，例如表情迁移、镜头扩图、局部重绘。",
      },
    ],
  };
}

module.exports = {
  createSeedData,
};
